'use client'
import { useEffect, useState } from 'react'
import dynamic from 'next/dynamic'
import { createClient } from '@/utils/supabase/client'
import { determineWinner, resolveVotes, isDeadlineReached } from '@/lib/game-rules'
const HostMap=dynamic(()=>import('@/components/HostMap'),{ssr:false}); const PlayerMap=dynamic(()=>import('@/components/PlayerMap'),{ssr:false})

function Meeting({ player, state, players, refresh }: any) {
  const supabase=createClient(); const [votes,setVotes]=useState<any[]>([]); const [seconds,setSeconds]=useState<number|null>(null); const [selectedVote,setSelectedVote]=useState<string | 'skip' | null>(null); const [resolving,setResolving]=useState(false); const [actionError,setActionError]=useState('')
  const getVotes=async()=>{const {data,error}=await supabase.from('meeting_votes').select('*');if(error){setActionError(`Could not load votes: ${error.message}`);return}setVotes(data||[])}
  useEffect(()=>{getVotes();const c=supabase.channel('votes').on('postgres_changes',{event:'*',schema:'public',table:'meeting_votes'},getVotes).subscribe();return()=>{ void supabase.removeChannel(c) }},[])
  useEffect(()=>{if(!state.meeting_ends_at){setActionError('Meeting timer is missing. Ask the host to restart the round.');return}const tick=()=>setSeconds(Math.max(0,Math.ceil((new Date(state.meeting_ends_at).getTime()-Date.now())/1000)));tick();const t=setInterval(tick,1000);return()=>clearInterval(t)},[state.meeting_ends_at])
  const vote=async(target:string|null)=>{if(player.status!=='alive'||seconds===0)return;setActionError('');const {error}=await supabase.from('meeting_votes').upsert({voter_id:player.id,target_id:target},{onConflict:'voter_id'});if(error){setActionError(`Vote was not saved: ${error.message}`);return}setSelectedVote(null);getVotes()}
  const mine=votes.find(v=>v.voter_id===player.id); const alive=players.filter((p:any)=>p.status==='alive')
  const finish=async()=>{if(state.status!=='meeting'||resolving)return;setResolving(true);setActionError('');try{const [{data:currentPlayers,error:playersError},{data:currentVotes,error:votesError}]=await Promise.all([supabase.from('players').select('*'),supabase.from('meeting_votes').select('*')]);if(playersError)throw playersError;if(votesError)throw votesError;const outcome=resolveVotes(currentPlayers||[],currentVotes||[]);const ejected=outcome.ejectedId?(currentPlayers||[]).find((p:any)=>p.id===outcome.ejectedId):null;const {data:transition,error:transitionError}=await supabase.from('game_state').update({status:'meeting_results',meeting_called_by:null,meeting_ends_at:null,results_ends_at:new Date(Date.now()+7000).toISOString(),vote_summary:outcome.summary,last_ejection_name:ejected?.name||'No one',last_ejection_role:ejected?.role||null}).eq('id',1).eq('status','meeting').select().maybeSingle();if(transitionError)throw transitionError;if(!transition)return;if(ejected){const {error}=await supabase.from('players').update({status:'ejected',death_kind:'ejected'}).eq('id',ejected.id);if(error)throw error}await supabase.from('meeting_votes').delete().neq('id','00000000-0000-0000-0000-000000000000');await refresh()}catch(error:any){setActionError(`Could not resolve meeting: ${error.message||'unknown connection error'}`)}finally{setResolving(false)}}
  useEffect(()=>{if(seconds!==null&&isDeadlineReached(state.meeting_ends_at))void finish()},[seconds])
  const selectedName=selectedVote==='skip'?'Skip vote':players.find((p:any)=>p.id===selectedVote)?.name
  return <div className="space-field fixed inset-0 z-[2000] flex items-center justify-center overflow-y-auto p-3">
    <div className="space-panel max-h-[calc(100dvh-1.5rem)] w-full max-w-2xl space-y-4 overflow-y-auto rounded-3xl border-2 border-red-500 p-5 text-center">
      <img src="/among-us/crewmate.png" alt="Crewmate" className="mx-auto h-16 w-14 object-contain" />
      <p className="font-black tracking-[.25em] text-red-400">EMERGENCY MEETING</p>
      {state.discord_url && <a href={state.discord_url} target="_blank" className="block rounded-2xl border-2 border-indigo-200 bg-indigo-600 py-3 font-bold shadow-[0_4px_0_#312e81]">Join Discord voting voice channel ↗</a>}
      <p className="sticky top-0 z-10 rounded-xl border border-slate-700 bg-slate-950/95 p-3 text-sm text-slate-300">Voting ends in <b className="text-amber-400">{seconds ?? '…'}s</b>. Votes lock when time expires.</p>
      {actionError && <p className="rounded-xl border border-red-500 bg-red-950/70 p-3 text-sm font-bold text-red-200">{actionError}</p>}
      <p className="rounded-xl border border-slate-700 bg-slate-950/60 p-3 text-xs text-slate-300">Hat on = alive. Hat off = dead. Dead players stay silent and cannot vote.</p>
      <div className="grid grid-cols-2 gap-3 sm:grid-cols-3">
        {players.map((p:any) => { const isAlive=p.status==='alive', chosen=selectedVote===p.id
          return <button key={p.id} disabled={!isAlive||player.status!=='alive'||seconds===0||resolving} onClick={()=>setSelectedVote(p.id)} className={`relative overflow-hidden rounded-2xl border-2 p-3 text-center transition ${chosen?'border-amber-300 bg-amber-400/20 ring-2 ring-amber-200':'border-slate-600 bg-slate-800'} ${!isAlive?'cursor-not-allowed opacity-45 grayscale':'hover:border-cyan-200'} disabled:cursor-not-allowed`}>
            <img src="/among-us/crewmate.png" alt="" className="mx-auto h-14 w-12 object-contain" style={{filter:isAlive?'none':'grayscale(1)'}} /><p className="mt-1 truncate font-black">{p.name}</p><p className={`text-[10px] font-black uppercase tracking-wider ${isAlive?'text-emerald-300':'text-red-300'}`}>{isAlive?'ALIVE · HAT ON':'DEAD · HAT OFF'}</p>{mine?.target_id===p.id&&<span className="absolute right-2 top-2 rounded bg-amber-400 px-1.5 py-0.5 text-[9px] font-black text-slate-950">VOTED</span>}
          </button>})}
      </div>
      <button disabled={player.status!=='alive'||seconds===0||resolving} onClick={()=>setSelectedVote('skip')} className={`w-full rounded-xl border-2 p-3 font-black ${selectedVote==='skip'?'border-amber-300 bg-amber-400/20':'border-slate-600 bg-slate-800'} disabled:cursor-not-allowed disabled:opacity-50`}>SKIP VOTE</button>
      {player.status==='alive' ? <button disabled={!selectedVote||seconds===0||resolving} onClick={()=>vote(selectedVote==='skip'?null:selectedVote)} className="w-full rounded-xl border-2 border-emerald-200 bg-emerald-600 py-3 font-black shadow-[0_4px_0_#166534] disabled:cursor-not-allowed disabled:border-slate-700 disabled:bg-slate-800 disabled:text-slate-500">{resolving?'RESOLVING VOTES…':selectedName?`CONFIRM VOTE: ${selectedName.toUpperCase()}`:'SELECT A PLAYER OR SKIP'}</button> : <p className="text-sm font-bold text-slate-400">You are dead and cannot vote.</p>}
      {mine&&<p className="text-xs font-bold text-amber-300">Vote submitted. You may change it before time expires.</p>}
      {player.is_host&&<button onClick={()=>void finish()} className="text-xs font-bold text-slate-400 underline">Host: end voting now</button>}
    </div>
  </div>
}

function Results({ player, state }: any) {
  const supabase=createClient(); const [seconds,setSeconds]=useState<number|null>(null)
  useEffect(()=>{const tick=()=>setSeconds(Math.max(0,Math.ceil((new Date(state.results_ends_at).getTime()-Date.now())/1000)));tick();const t=setInterval(tick,300);return()=>clearInterval(t)},[state.results_ends_at])
  const advance=async()=>{if(state.status!=='meeting_results')return;const [{data:p},{data:t}]=await Promise.all([supabase.from('players').select('*'),supabase.from('player_tasks').select('is_completed')]);const winner=determineWinner(p||[],t||[]);await supabase.from('game_state').update(winner?{status:'ended',winner,results_ends_at:new Date(Date.now()+7000).toISOString()}:{status:'playing',vote_summary:null,results_ends_at:null}).eq('id',1)}
  useEffect(()=>{if(seconds===0)advance()},[seconds])
  const reveal=seconds!==null&&seconds<=4
  return <div className="space-field fixed inset-0 z-[2000] grid place-items-center overflow-y-auto p-5"><div className="space-panel w-full max-w-md rounded-3xl border-2 border-slate-500 p-7 text-center">{!reveal?<><p className="font-black tracking-[.2em] text-amber-400">VOTING RESULTS</p><h2 className="my-4 text-2xl font-black">Votes received</h2><div className="space-y-2 text-left">{Object.entries(state.vote_summary||{}).map(([name,count])=><div key={name} className="flex justify-between rounded-xl border border-slate-600 bg-slate-800 px-4 py-3 font-bold"><span>{name}</span><span>{String(count)} vote{Number(count)===1?'':'s'}</span></div>)}</div></>:<><img src="/among-us/crewmate.png" alt="Crewmate" className="mx-auto h-24 w-20 object-contain"/><p className="font-black tracking-[.2em] text-red-400">EJECTION RESULT</p><h2 className="my-5 text-3xl font-black">{state.last_ejection_name==='No one'?'No one was ejected.':`${state.last_ejection_name} was ${state.last_ejection_role==='imposter'?'an IMPOSTER!':'NOT an imposter.'}`}</h2><p className="rounded-xl bg-indigo-950 p-3 text-sm font-bold text-indigo-200">Leave the Discord voting voice channel before the next round starts.</p></>}<p className="mt-5 text-sm text-slate-400">Continuing in {seconds??'…'}s</p></div></div>
}

function WinScreen({ player, state }: any) {
  const supabase=createClient(); const [seconds,setSeconds]=useState<number|null>(null)
  useEffect(()=>{const tick=()=>setSeconds(Math.max(0,Math.ceil((new Date(state.results_ends_at).getTime()-Date.now())/1000)));tick();const t=setInterval(tick,300);return()=>clearInterval(t)},[state.results_ends_at])
  const lobby=async()=>{if(state.status!=='ended')return;await supabase.from('player_tasks').delete().neq('id','00000000-0000-0000-0000-000000000000');await supabase.from('players').update({role:null,status:'alive',kill_available_at:null,killed_at:null,death_kind:null}).neq('id','00000000-0000-0000-0000-000000000000');await supabase.from('game_state').update({status:'lobby',winner:null,results_ends_at:null,vote_summary:null}).eq('id',1)}
  useEffect(()=>{if(seconds===0)lobby()},[seconds])
  const crewmatesWon=state.winner==='crewmates'
  const didWin=(crewmatesWon&&player.role==='crewmate')||(!crewmatesWon&&player.role==='imposter')
  const accent=crewmatesWon?'cyan':'red'
  return <div className={`space-field fixed inset-0 z-[2000] grid place-items-center p-5 text-center ${crewmatesWon?'bg-cyan-950/25':'bg-red-950/35'}`}><div className={`space-panel w-full max-w-lg rounded-[2rem] border-4 p-10 ${crewmatesWon?'border-cyan-300':'border-red-500'}`}><img src="/among-us/crewmate.png" alt="Crewmate" className={`mx-auto h-36 w-28 object-contain ${crewmatesWon?'':'hue-rotate-[325deg] saturate-150'}`}/><p className={`text-sm font-black tracking-[.32em] ${crewmatesWon?'text-cyan-300':'text-red-400'}`}>GAME OVER</p><h2 className="my-4 text-5xl font-black tracking-tight text-white">{crewmatesWon?'CREWMATES WIN':'IMPOSTERS WIN'}</h2><p className={`mx-auto mb-6 max-w-sm text-lg font-bold ${didWin?'text-emerald-300':'text-slate-300'}`}>{didWin?'VICTORY — your team completed its objective.':'DEFEAT — the other team completed its objective.'}</p><div className="rounded-2xl border border-slate-600 bg-slate-950/70 p-4 text-sm text-slate-300">{crewmatesWon?'All imposters were removed or every assigned task was completed.':'Imposters now equal or outnumber the remaining crewmates.'}</div><p className="mt-6 text-sm font-bold text-slate-400">Returning to lobby in {seconds??'…'}s</p></div></div>
}

export default function Home(){
 const supabase=createClient();const [player,setPlayer]=useState<any>(null),[name,setName]=useState(''),[state,setState]=useState<any>(null),[players,setPlayers]=useState<any[]>([]),[hostMap,setHostMap]=useState(false),[imposters,setImposters]=useState(1),[discord,setDiscord]=useState(''),[notice,setNotice]=useState('')
 const refresh=async()=>{let {data:s}=await supabase.from('game_state').select('*').eq('id',1).single();if(!s){const {data}=await supabase.from('game_state').insert({id:1,status:'lobby'}).select().single();s=data}setState(s);const {data:p}=await supabase.from('players').select('*').order('name');setPlayers(p||[]);const saved=localStorage.getItem('among-us-player');if(saved&&!player){const me=(p||[]).find((x:any)=>x.id===saved);if(me)setPlayer(me)}}
 useEffect(()=>{refresh();const c=supabase.channel('lobby').on('postgres_changes',{event:'*',schema:'public',table:'game_state'},refresh).on('postgres_changes',{event:'*',schema:'public',table:'players'},refresh).on('postgres_changes',{event:'*',schema:'public',table:'player_tasks'},()=>{refresh();checkWin()}).subscribe();return()=>{ void supabase.removeChannel(c) }},[])
 useEffect(()=>{if(state?.status==='playing')checkWin()},[state?.status,players.length])
 useEffect(()=>{if(player){const current=players.find(p=>p.id===player.id);if(current&&current!==player)setPlayer(current)}},[players])
 useEffect(()=>{if(player&&!players.some(p=>p.id===player.id)){localStorage.removeItem('among-us-player');setPlayer(null);setNotice('You were removed from this game.')}},[players,player])
 const checkWin=async()=>{const {data:p}=await supabase.from('players').select('*');if(!p||p.length<2)return;const {data:t}=await supabase.from('player_tasks').select('is_completed');const winner=determineWinner(p,t||[]);if(winner)await supabase.from('game_state').update({status:'ended',winner,results_ends_at:new Date(Date.now()+7000).toISOString()}).eq('id',1)}
 const join=async(e:any)=>{e.preventDefault();const clean=name.trim();if(!clean)return;const {data:existing,error:lookupError}=await supabase.from('players').select('*').eq('name',clean).maybeSingle();if(lookupError){setNotice(`Could not look up player: ${lookupError.message}`);return}if(existing){await supabase.from('players').update({disconnected_at:null}).eq('id',existing.id);const restored={...existing,disconnected_at:null};localStorage.setItem('among-us-player',existing.id);setPlayers(current=>current.some(p=>p.id===existing.id)?current.map(p=>p.id===existing.id?restored:p):[...current,restored]);setPlayer(restored);setNotice(`Reconnected as ${existing.name}.`);await refresh();return}const {data,error}=await supabase.from('players').insert({name:clean,role:null,status:'alive',is_host:players.length===0}).select().single();if(error){setNotice('That name is already in use. Choose a different name.');return}setPlayers(current=>[...current,data]);localStorage.setItem('among-us-player',data.id);setPlayer(data);await refresh()}
 const disconnect=async()=>{if(player)await supabase.from('players').update({disconnected_at:new Date().toISOString()}).eq('id',player.id);localStorage.removeItem('among-us-player');setPlayer(null);setNotice('Disconnected from this browser. Enter the same exact name to reconnect.')}
 const start=async()=>{const {data:p}=await supabase.from('players').select('*');const {data:templates}=await supabase.from('task_templates').select('*');if(!p||p.length<4){alert('At least four players are required to start a game.');return}await supabase.from('player_tasks').delete().neq('id','00000000-0000-0000-0000-000000000000');const shuffled=[...p].sort(()=>Math.random()-.5),n=Math.min(imposters,Math.max(1,p.length-1));await Promise.all(shuffled.map(async(x,i)=>{const role=i<n?'imposter':'crewmate';const {error}=await supabase.from('players').update({role,status:'alive'}).eq('id',x.id);if(error)throw error;await supabase.from('players').update({kill_available_at:null,killed_at:null,death_kind:null}).eq('id',x.id);if(role==='crewmate'&&templates?.length){const tasks=[...templates].sort(()=>Math.random()-.5).slice(0,Math.min(5,templates.length)).map(t=>({player_id:x.id,title:t.title,lat:t.lat,lng:t.lng,is_completed:false}));await supabase.from('player_tasks').insert(tasks)}}));await supabase.from('game_state').update({status:'playing',winner:null,discord_url:discord||null,last_ejection_name:null}).eq('id',1)}
 const emergency=async(button:any)=>{if(state?.status!=='playing')return;await supabase.from('meeting_votes').delete().neq('id','00000000-0000-0000-0000-000000000000');await supabase.from('game_state').update({status:'meeting',meeting_called_by:player.id,meeting_ends_at:new Date(Date.now()+120000).toISOString()}).eq('id',1)}
 const restart=async()=>{const {error:taskError}=await supabase.from('player_tasks').delete().neq('id','00000000-0000-0000-0000-000000000000');if(taskError){alert(`Could not clear tasks: ${taskError.message}`);return}const {error:playerError}=await supabase.from('players').update({role:null,status:'alive'}).neq('id','00000000-0000-0000-0000-000000000000');if(playerError){alert(`Could not reset players: ${playerError.message}`);return}await supabase.from('players').update({kill_available_at:null,killed_at:null,death_kind:null}).neq('id','00000000-0000-0000-0000-000000000000');const {error:stateError}=await supabase.from('game_state').update({status:'lobby',winner:null,meeting_ends_at:null,results_ends_at:null,vote_summary:null}).eq('id',1);if(stateError){alert(`Could not return to lobby: ${stateError.message}`);return}await refresh()}
 const restartWithNewPlayers=async()=>{if(!confirm('Remove every player and return to an empty lobby?'))return;await supabase.from('player_tasks').delete().neq('id','00000000-0000-0000-0000-000000000000');await supabase.from('players').delete().neq('id','00000000-0000-0000-0000-000000000000');await supabase.from('game_state').update({status:'lobby',winner:null,meeting_ends_at:null}).eq('id',1);localStorage.removeItem('among-us-player');setPlayer(null)}
 const kick=async(id:string)=>{if(!confirm('Remove this player from the game?'))return;await supabase.from('player_tasks').delete().eq('player_id',id);await supabase.from('players').delete().eq('id',id)}
 if(!player)return <main className="space-field flex min-h-screen items-center justify-center overflow-hidden p-6 text-white"><form onSubmit={join} className="space-panel relative w-full max-w-md space-y-4 rounded-3xl p-8"><img src="/among-us/crewmate.png" alt="Crewmate" className="mx-auto h-36 w-32 object-contain"/><h1 className="text-center text-3xl font-black tracking-[.18em] text-white">IRL AMONG US</h1><p className="text-center text-sm text-slate-400">Use your exact existing name on a new tab/device to reconnect.</p>{notice&&<p className="text-sm text-amber-300">{notice}</p>}<input value={name} onChange={e=>setName(e.target.value)} placeholder="Your unique player name" className="w-full rounded-2xl border-2 border-slate-600 bg-slate-800 p-4 font-bold" required/><button className="w-full rounded-2xl border-2 border-red-200 bg-gradient-to-b from-red-500 to-red-800 py-4 font-black shadow-[0_5px_0_#7f1d1d]">JOIN / RECONNECT</button></form></main>
 if(state?.status==='lobby')return <main className="min-h-screen bg-slate-950 p-6 text-white"><div className="mx-auto max-w-xl space-y-5 rounded-3xl border border-slate-800 bg-slate-900 p-6"><div className="flex justify-between"><h1 className="text-2xl font-black text-amber-400">GAME LOBBY</h1><button onClick={disconnect} className="text-sm font-bold text-slate-400">Disconnect browser</button></div><div className="rounded-2xl bg-slate-950 p-4">{players.map(p=><div key={p.id} className="flex items-center justify-between py-1 font-bold"><span>{p.name} {p.is_host&&'👑'} {p.disconnected_at&&<small className="ml-2 text-slate-500">offline</small>}</span>{player.is_host&&p.id!==player.id&&<button onClick={()=>kick(p.id)} className="rounded bg-red-950 px-2 py-1 text-xs text-red-300">Kick</button>}</div>)}</div>{player.is_host?<div className="space-y-3 border-t border-slate-800 pt-4"><select value={imposters} onChange={e=>setImposters(+e.target.value)} className="w-full rounded-xl bg-slate-800 p-3">{[1,2,3].map(n=><option key={n} value={n}>{n} imposters</option>)}</select><input value={discord} onChange={e=>setDiscord(e.target.value)} placeholder="Optional Discord invite URL" className="w-full rounded-xl bg-slate-800 p-3"/><button onClick={()=>setHostMap(true)} className="w-full rounded-xl bg-slate-700 py-3 font-bold">Set up map markers & task types</button><button onClick={start} className="w-full rounded-xl bg-emerald-600 py-4 font-black">START GAME</button><button onClick={restartWithNewPlayers} className="w-full rounded-xl border border-red-800 py-3 text-sm font-bold text-red-300">Restart with new players (clear lobby)</button></div>:<p className="text-center text-slate-400">Waiting for the host…</p>}</div>{hostMap&&<HostMap onClose={()=>setHostMap(false)}/>}</main>
 return <main className="min-h-screen bg-slate-950 p-4 text-white"><div className="mx-auto max-w-xl space-y-4"><header className="flex items-center justify-between rounded-2xl border border-slate-800 bg-slate-900 p-4"><div><b>{player.name}</b><p className={player.role==='imposter'?'text-sm font-black text-red-400':'text-sm font-black text-emerald-400'}>{player.role}</p></div><div className="flex gap-2">{player.is_host&&<><button onClick={restart} className="rounded-xl bg-amber-600 px-3 py-2 text-xs font-bold">Restart same</button><button onClick={restartWithNewPlayers} className="rounded-xl border border-red-800 px-3 py-2 text-xs font-bold text-red-300">New players</button></>}<button onClick={disconnect} className="text-xs font-bold text-slate-400">Disconnect</button></div></header>{state?.status!=='ended'&&<PlayerMap player={player} gameState={state} onEmergency={emergency}/>}</div>{state?.status==='meeting'&&<Meeting player={player} state={state} players={players} refresh={refresh}/>} {state?.status==='meeting_results'&&<Results player={player} state={state}/>} {state?.status==='ended'&&<WinScreen player={player} state={state}/>}</main>
}
