'use client'
import { useEffect, useState } from 'react'
import dynamic from 'next/dynamic'
import { createClient } from '@/utils/supabase/client'
const HostMap=dynamic(()=>import('@/components/HostMap'),{ssr:false}); const PlayerMap=dynamic(()=>import('@/components/PlayerMap'),{ssr:false})

function Meeting({ player, state, players, refresh }: any) {
  const supabase=createClient(); const [votes,setVotes]=useState<any[]>([]); const [seconds,setSeconds]=useState<number|null>(null)
  const getVotes=async()=>{const {data}=await supabase.from('meeting_votes').select('*');setVotes(data||[])}
  useEffect(()=>{getVotes();const c=supabase.channel('votes').on('postgres_changes',{event:'*',schema:'public',table:'meeting_votes'},getVotes).subscribe();return()=>{ void supabase.removeChannel(c) }},[])
  useEffect(()=>{const tick=()=>setSeconds(Math.max(0,Math.ceil((new Date(state.meeting_ends_at).getTime()-Date.now())/1000)));tick();const t=setInterval(tick,500);return()=>clearInterval(t)},[state.meeting_ends_at])
  const vote=async(target:string|null)=>{if(player.status!=='alive')return;await supabase.from('meeting_votes').upsert({voter_id:player.id,target_id:target},{onConflict:'voter_id'});getVotes()}
  const mine=votes.find(v=>v.voter_id===player.id); const alive=players.filter((p:any)=>p.status==='alive')
  const finish=async()=>{ if(state.status!=='meeting')return; const counts=new Map<string,number>(); votes.forEach(v=>counts.set(v.target_id||'skip',(counts.get(v.target_id||'skip')||0)+1)); let winner='skip',high=0,tie=false; counts.forEach((n,id)=>{if(n>high){winner=id;high=n;tie=false}else if(n===high)tie=true}); const ejected=!tie&&winner!=='skip'?players.find((p:any)=>p.id===winner):null; if(ejected) await supabase.from('players').update({status:'ejected',death_kind:'ejected'}).eq('id',ejected.id); const summary=Object.fromEntries([...alive.map((p:any)=>[p.name,counts.get(p.id)||0]),['Skip',counts.get('skip')||0]]); await supabase.from('meeting_votes').delete().neq('id','00000000-0000-0000-0000-000000000000'); await supabase.from('game_state').update({status:'meeting_results',meeting_called_by:null,meeting_ends_at:null,results_ends_at:new Date(Date.now()+7000).toISOString(),vote_summary:summary,last_ejection_name:ejected?.name||'No one',last_ejection_role:ejected?.role||null}).eq('id',1); refresh() }
  useEffect(()=>{if(seconds===0&&state.meeting_ends_at)finish()},[seconds])
  return <div className="fixed inset-0 z-[2000] flex items-center justify-center bg-slate-950/95 p-5"><div className="w-full max-w-lg space-y-5 rounded-3xl border border-red-500 bg-slate-900 p-6 text-center shadow-2xl"><p className="font-black tracking-[.25em] text-red-500">EMERGENCY MEETING</p><h2 className="text-3xl font-black">Discuss, then vote</h2>{state.discord_url&&<a href={state.discord_url} target="_blank" className="block rounded-2xl bg-indigo-600 py-3 font-bold">Join Discord voting voice channel ↗</a>}<p className="text-sm text-slate-400">Open Discord to discuss, then return here to vote. Voting ends in <b className="text-amber-400">{seconds ?? '…'}s</b>.</p><div className="grid gap-2">{alive.map((p:any)=><button key={p.id} disabled={player.status!=='alive'} onClick={()=>vote(p.id)} className={`rounded-xl border p-3 text-left font-bold ${mine?.target_id===p.id?'border-amber-400 bg-amber-400/15':'border-slate-700 bg-slate-800'}`}>{p.name}</button>)}<button disabled={player.status!=='alive'} onClick={()=>vote(null)} className={`rounded-xl border p-3 font-bold ${mine?.target_id===null?'border-amber-400 bg-amber-400/15':'border-slate-700'}`}>SKIP VOTE</button></div>{player.is_host&&<button onClick={finish} className="text-xs font-bold text-slate-400 underline">Host: end voting now</button>}</div></div>
}

function Results({ player, state }: any) {
  const supabase=createClient(); const [seconds,setSeconds]=useState<number|null>(null)
  useEffect(()=>{const tick=()=>setSeconds(Math.max(0,Math.ceil((new Date(state.results_ends_at).getTime()-Date.now())/1000)));tick();const t=setInterval(tick,300);return()=>clearInterval(t)},[state.results_ends_at])
  const advance=async()=>{if(state.status!=='meeting_results')return;const {data:p}=await supabase.from('players').select('*');const alive=(p||[]).filter(x=>x.status==='alive'),imps=alive.filter(x=>x.role==='imposter'),crew=alive.filter(x=>x.role==='crewmate');const winner=!imps.length?'crewmates':imps.length>=crew.length?'imposters':'';await supabase.from('game_state').update(winner?{status:'ended',winner,results_ends_at:new Date(Date.now()+7000).toISOString()}:{status:'playing',vote_summary:null,results_ends_at:null}).eq('id',1)}
  useEffect(()=>{if(seconds===0)advance()},[seconds])
  const reveal=seconds!==null&&seconds<=4
  return <div className="fixed inset-0 z-[2000] grid place-items-center bg-slate-950/95 p-5"><div className="w-full max-w-md rounded-3xl border border-amber-400 bg-slate-900 p-7 text-center shadow-2xl">{!reveal?<><p className="font-black tracking-[.2em] text-amber-400">VOTING RESULTS</p><h2 className="my-4 text-2xl font-black">Votes received</h2><div className="space-y-2 text-left">{Object.entries(state.vote_summary||{}).map(([name,count])=><div key={name} className="flex justify-between rounded-xl bg-slate-800 px-4 py-3 font-bold"><span>{name}</span><span>{String(count)} vote{Number(count)===1?'':'s'}</span></div>)}</div></>:<><p className="font-black tracking-[.2em] text-red-400">EJECTION RESULT</p><h2 className="my-5 text-3xl font-black">{state.last_ejection_name==='No one'?'No one was ejected.':`${state.last_ejection_name} was ${state.last_ejection_role==='imposter'?'an IMPOSTER!':'NOT an imposter.'}`}</h2><p className="rounded-xl bg-indigo-950 p-3 text-sm font-bold text-indigo-200">Leave the Discord voting voice channel before the next round starts.</p></>}<p className="mt-5 text-sm text-slate-400">Continuing in {seconds??'…'}s</p></div></div>
}

function WinScreen({ player, state }: any) {
  const supabase=createClient(); const [seconds,setSeconds]=useState<number|null>(null)
  useEffect(()=>{const tick=()=>setSeconds(Math.max(0,Math.ceil((new Date(state.results_ends_at).getTime()-Date.now())/1000)));tick();const t=setInterval(tick,300);return()=>clearInterval(t)},[state.results_ends_at])
  const lobby=async()=>{if(state.status!=='ended')return;await supabase.from('player_tasks').delete().neq('id','00000000-0000-0000-0000-000000000000');await supabase.from('players').update({role:null,status:'alive',kill_available_at:null,killed_at:null,death_kind:null}).neq('id','00000000-0000-0000-0000-000000000000');await supabase.from('game_state').update({status:'lobby',winner:null,results_ends_at:null,vote_summary:null}).eq('id',1)}
  useEffect(()=>{if(seconds===0)lobby()},[seconds])
  return <div className="fixed inset-0 z-[2000] grid place-items-center bg-slate-950 p-5 text-center"><div className="w-full max-w-md rounded-3xl border border-amber-400 bg-slate-900 p-10"><p className="text-sm font-black tracking-[.25em] text-amber-400">GAME OVER</p><h2 className="my-4 text-4xl font-black text-white">{state.winner?.toUpperCase()} WIN!</h2><p className="text-slate-400">Returning to the lobby in {seconds??'…'}s</p></div></div>
}

export default function Home(){
 const supabase=createClient();const [player,setPlayer]=useState<any>(null),[name,setName]=useState(''),[state,setState]=useState<any>(null),[players,setPlayers]=useState<any[]>([]),[hostMap,setHostMap]=useState(false),[imposters,setImposters]=useState(1),[discord,setDiscord]=useState(''),[notice,setNotice]=useState('')
 const refresh=async()=>{let {data:s}=await supabase.from('game_state').select('*').eq('id',1).single();if(!s){const {data}=await supabase.from('game_state').insert({id:1,status:'lobby'}).select().single();s=data}setState(s);const {data:p}=await supabase.from('players').select('*').order('name');setPlayers(p||[]);const saved=localStorage.getItem('among-us-player');if(saved&&!player){const me=(p||[]).find((x:any)=>x.id===saved);if(me)setPlayer(me)}}
 useEffect(()=>{refresh();const c=supabase.channel('lobby').on('postgres_changes',{event:'*',schema:'public',table:'game_state'},refresh).on('postgres_changes',{event:'*',schema:'public',table:'players'},refresh).on('postgres_changes',{event:'*',schema:'public',table:'player_tasks'},()=>{refresh();checkWin()}).subscribe();return()=>{ void supabase.removeChannel(c) }},[])
 useEffect(()=>{if(state?.status==='playing')checkWin()},[state?.status,players.length])
 useEffect(()=>{if(player){const current=players.find(p=>p.id===player.id);if(current&&current!==player)setPlayer(current)}},[players])
 useEffect(()=>{if(player&&!players.some(p=>p.id===player.id)){localStorage.removeItem('among-us-player');setPlayer(null);setNotice('You were removed from this game.')}},[players,player])
 const checkWin=async()=>{const {data:p}=await supabase.from('players').select('*');if(!p||p.length<2)return;const alive=p.filter(x=>x.status==='alive'),imps=alive.filter(x=>x.role==='imposter'),crew=alive.filter(x=>x.role==='crewmate');const {data:t}=await supabase.from('player_tasks').select('is_completed');let winner='';if(!imps.length)winner='crewmates';else if(imps.length>=crew.length)winner='imposters';else if(t?.length&&t.every(x=>x.is_completed))winner='crewmates';if(winner)await supabase.from('game_state').update({status:'ended',winner,results_ends_at:new Date(Date.now()+7000).toISOString()}).eq('id',1)}
 const join=async(e:any)=>{e.preventDefault();const clean=name.trim();if(!clean)return;const existing=players.find(p=>p.name===clean);if(existing){await supabase.from('players').update({disconnected_at:null}).eq('id',existing.id);localStorage.setItem('among-us-player',existing.id);setPlayer({...existing,disconnected_at:null});setNotice(`Reconnected as ${existing.name}.`);return}const {data,error}=await supabase.from('players').insert({name:clean,role:null,status:'alive',is_host:players.length===0}).select().single();if(error){setNotice('That name is already in use. Choose a different name.');return}setPlayers(current=>[...current,data]);localStorage.setItem('among-us-player',data.id);setPlayer(data)}
 const disconnect=async()=>{if(player)await supabase.from('players').update({disconnected_at:new Date().toISOString()}).eq('id',player.id);localStorage.removeItem('among-us-player');setPlayer(null);setNotice('Disconnected from this browser. Enter the same exact name to reconnect.')}
 const start=async()=>{const {data:p}=await supabase.from('players').select('*');const {data:templates}=await supabase.from('task_templates').select('*');if(!p?.length)return;await supabase.from('player_tasks').delete().neq('id','00000000-0000-0000-0000-000000000000');const shuffled=[...p].sort(()=>Math.random()-.5),n=Math.min(imposters,Math.max(1,p.length-1));await Promise.all(shuffled.map(async(x,i)=>{const role=i<n?'imposter':'crewmate';await supabase.from('players').update({role,status:'alive',kill_available_at:null,killed_at:null,death_kind:null}).eq('id',x.id);if(role==='crewmate'&&templates?.length){const tasks=[...templates].sort(()=>Math.random()-.5).slice(0,Math.min(5,templates.length)).map(t=>({player_id:x.id,title:t.title,lat:t.lat,lng:t.lng,is_completed:false}));await supabase.from('player_tasks').insert(tasks)}}));await supabase.from('game_state').update({status:'playing',winner:null,discord_url:discord||null,last_ejection_name:null}).eq('id',1)}
 const emergency=async(button:any)=>{if(state?.status!=='playing')return;await supabase.from('meeting_votes').delete().neq('id','00000000-0000-0000-0000-000000000000');await supabase.from('game_state').update({status:'meeting',meeting_called_by:player.id,meeting_ends_at:new Date(Date.now()+120000).toISOString()}).eq('id',1)}
 const restart=async()=>{await supabase.from('player_tasks').delete().neq('id','00000000-0000-0000-0000-000000000000');await supabase.from('players').update({role:null,status:'alive',kill_available_at:null,killed_at:null,death_kind:null}).neq('id','00000000-0000-0000-0000-000000000000');await supabase.from('game_state').update({status:'lobby',winner:null,meeting_ends_at:null}).eq('id',1)}
 const restartWithNewPlayers=async()=>{if(!confirm('Remove every player and return to an empty lobby?'))return;await supabase.from('player_tasks').delete().neq('id','00000000-0000-0000-0000-000000000000');await supabase.from('players').delete().neq('id','00000000-0000-0000-0000-000000000000');await supabase.from('game_state').update({status:'lobby',winner:null,meeting_ends_at:null}).eq('id',1);localStorage.removeItem('among-us-player');setPlayer(null)}
 const kick=async(id:string)=>{if(!confirm('Remove this player from the game?'))return;await supabase.from('player_tasks').delete().eq('player_id',id);await supabase.from('players').delete().eq('id',id)}
 if(!player)return <main className="flex min-h-screen items-center justify-center bg-slate-950 p-6 text-white"><form onSubmit={join} className="w-full max-w-md space-y-4 rounded-3xl border border-slate-800 bg-slate-900 p-8"><h1 className="text-center text-3xl font-black text-red-500">IRL AMONG US</h1><p className="text-sm text-slate-400">Use your exact existing name on a new tab/device to reconnect.</p>{notice&&<p className="text-sm text-amber-300">{notice}</p>}<input value={name} onChange={e=>setName(e.target.value)} placeholder="Your unique player name" className="w-full rounded-2xl border border-slate-700 bg-slate-800 p-4 font-bold" required/><button className="w-full rounded-2xl bg-red-600 py-4 font-black">JOIN / RECONNECT</button></form></main>
 if(state?.status==='lobby')return <main className="min-h-screen bg-slate-950 p-6 text-white"><div className="mx-auto max-w-xl space-y-5 rounded-3xl border border-slate-800 bg-slate-900 p-6"><div className="flex justify-between"><h1 className="text-2xl font-black text-amber-400">GAME LOBBY</h1><button onClick={disconnect} className="text-sm font-bold text-slate-400">Disconnect browser</button></div><div className="rounded-2xl bg-slate-950 p-4">{players.map(p=><div key={p.id} className="flex items-center justify-between py-1 font-bold"><span>{p.name} {p.is_host&&'👑'} {p.disconnected_at&&<small className="ml-2 text-slate-500">offline</small>}</span>{player.is_host&&p.id!==player.id&&<button onClick={()=>kick(p.id)} className="rounded bg-red-950 px-2 py-1 text-xs text-red-300">Kick</button>}</div>)}</div>{player.is_host?<div className="space-y-3 border-t border-slate-800 pt-4"><select value={imposters} onChange={e=>setImposters(+e.target.value)} className="w-full rounded-xl bg-slate-800 p-3">{[1,2,3].map(n=><option key={n} value={n}>{n} imposters</option>)}</select><input value={discord} onChange={e=>setDiscord(e.target.value)} placeholder="Optional Discord invite URL" className="w-full rounded-xl bg-slate-800 p-3"/><button onClick={()=>setHostMap(true)} className="w-full rounded-xl bg-slate-700 py-3 font-bold">Set up map markers & task types</button><button onClick={start} className="w-full rounded-xl bg-emerald-600 py-4 font-black">START GAME</button><button onClick={restartWithNewPlayers} className="w-full rounded-xl border border-red-800 py-3 text-sm font-bold text-red-300">Restart with new players (clear lobby)</button></div>:<p className="text-center text-slate-400">Waiting for the host…</p>}</div>{hostMap&&<HostMap onClose={()=>setHostMap(false)}/>}</main>
 return <main className="min-h-screen bg-slate-950 p-4 text-white"><div className="mx-auto max-w-xl space-y-4"><header className="flex items-center justify-between rounded-2xl border border-slate-800 bg-slate-900 p-4"><div><b>{player.name}</b><p className={player.role==='imposter'?'text-sm font-black text-red-400':'text-sm font-black text-emerald-400'}>{player.role}</p></div><div className="flex gap-2">{player.is_host&&<><button onClick={restart} className="rounded-xl bg-amber-600 px-3 py-2 text-xs font-bold">Restart same</button><button onClick={restartWithNewPlayers} className="rounded-xl border border-red-800 px-3 py-2 text-xs font-bold text-red-300">New players</button></>}<button onClick={disconnect} className="text-xs font-bold text-slate-400">Disconnect</button></div></header>{state?.status!=='ended'&&<PlayerMap player={player} gameState={state} onEmergency={emergency}/>}</div>{state?.status==='meeting'&&<Meeting player={player} state={state} players={players} refresh={refresh}/>} {state?.status==='meeting_results'&&<Results player={player} state={state}/>} {state?.status==='ended'&&<WinScreen player={player} state={state}/>}</main>
}
